### ISSUE TITLE
Confusion with a Challenge for Fluoride - Auto Team

### ISSUE THREAD

**Issue by SambaSowe** [AguaClara/Fluoride-Auto#65]
In the AguaClara challenges, what did you mean by "Measure the required flow rate of the waste stream as a baseline of the percent of the total flow that will be wasted if additional concentration steps aren’t invented and implemented".

**Comment by monroews** [comment]
Waste management will be a critical part of any system that removes fluoride or arsenic. Thus we need to begin to quantify how much waste the system produces. As a first step you can run the waste stream as slowly as possible (so that the flocs can consolidate) and measure the flow rate required. From that you can calculate how big this waste stream will be for a plant and begin thinking about how you will manage that waste stream.
